trigger:
- master

variables:
  dockerRegistryServiceConnection: '44374573-4bde-49d1-be4c-e36ff30bc33b'
  imageRepository: 'apicashflow'
  containerRegistry: 'apicashflow.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  # vmImageName: 'ubuntu-latest'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: appsettings
  displayName: 'Download AppSettings.json'
  inputs:
    secureFile: 'appsettings.Production.json'

- script: |
    cp $(appsettings.secureFilePath) src/CashFlow.Api/appsettings.Production.json

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)

# stages:
# - stage: Build
#   displayName: Build and push stage
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: $(vmImageName)
#     steps:

#     - task: Docker@2
#       displayName: Build and push an image to container registry
#       inputs:
#         command: buildAndPush
#         repository: $(imageRepository)
#         dockerfile: $(dockerfilePath)
#         containerRegistry: $(dockerRegistryServiceConnection)
#         tags: |
#           $(tag)